<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>Acontplus.Common.FactElect</PackageId>
    <Version>0.1.5</Version>
    <Authors>Ivan Paz</Authors>
    <Company>Acontplus S.A.S.</Company>
    <Description>Lib to use facturación electronica SRI Ecuador</Description>
    <PackageTags>facturacion;sri;ecuador;services-sri</PackageTags>
    <RepositoryUrl>https://github.com/Acontplus-S-A-S/acontplus-common</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>icon.png</PackageIcon>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Schemas\comprobanteRetencion_V1.0.0.xsd" />
    <None Remove="Schemas\comprobanteRetencion_V2.0.0.xsd" />
    <None Remove="Schemas\factura_V1.0.0.xsd" />
    <None Remove="Schemas\factura_V1.1.0.xsd" />
    <None Remove="Schemas\factura_V2.0.0.xsd" />
    <None Remove="Schemas\factura_V2.1.0.xsd" />
    <None Remove="Schemas\NotaCredito_V1.0.0.xsd" />
    <None Remove="Schemas\NotaCredito_V1.1.0.xsd" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Images\icon.png">
      <PackagePath>\</PackagePath>
      <Pack>True</Pack>
    </EmbeddedResource>
    <EmbeddedResource Include="Schemas\comprobanteRetencion_V1.0.0.xsd">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Schemas\comprobanteRetencion_V2.0.0.xsd">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Schemas\factura_V1.0.0.xsd">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Schemas\factura_V1.1.0.xsd">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Schemas\factura_V2.0.0.xsd">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Schemas\factura_V2.1.0.xsd">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Schemas\NotaCredito_V1.0.0.xsd">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Schemas\NotaCredito_V1.1.0.xsd">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Acontplus.Common.Barcode" />
    <PackageReference Include="Acontplus.Common.Core" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>
  <ItemGroup>
    <None Update="README.md">
      <PackagePath>\</PackagePath>
      <Pack>true</Pack>
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>