<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>Acontplus.FactElect.Application</PackageId>
    <Version>1.0.1</Version>
    <Authors>Ivan Paz</Authors>
    <Company>Acontplus S.A.S.</Company>
    <Description>Lib to use facturación electronica SRI Ecuador</Description>
    <PackageTags>facturacion;sri;ecuador;services-sri</PackageTags>
    <RepositoryUrl>https://github.com/Acontplus-S-A-S/acontplus-common</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Acontplus.Common.Core" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>
  <ItemGroup>
    <None Update="README.md">
      <PackagePath>\</PackagePath>
      <Pack>true</Pack>
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>