@Common.TestApi_HostAddress = https://localhost:7111

GET {{Common.TestApi_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{Common.TestApi_HostAddress}}/api/barcode

###

POST {{Common.TestApi_HostAddress}}/api/usuario
Content-Type: application/json

{
  "username": "ivan",
  "email": "ifer343@gmail.com"
}

###

@id=2
PUT {{Common.TestApi_HostAddress}}/api/usuario/{{id}}
Content-Type: application/json

{
  "username": "ivan.paz",
  "email": "ifer343@gmail.com"
}

###
